[variables]
NPM_CONFIG_UPDATE_NOTIFIER = "false"
NPM_CONFIG_FUND = "false"

[phases.setup]
nixPkgs = ["caddy"]

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["bun run build"]

[start]
cmd = "caddy run --config Caddyfile --adapter caddyfile" 